### ISSUE TITLE
Build problem?

### ISSUE THREAD

**Issue by jennylia** [Microsquad/gitpizza#1]
Hi Joseph, 
Cool idea!
I tried to order a pizza with gitpizza but I can't run this python script.
Have you seen these problems before?
Can you give me some pointers to what is going on?

Cheers,
Jenny

```
dhcp-128-189-229-5:gitpizza jennylian$ python3.5 gitpizza.py 
Traceback (most recent call last):
  File "gitpizza.py", line 663, in <module>
    with shelve.open(shelve_fullname, 'r') as shelf:
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/shelve.py", line 243, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/shelve.py", line 227, in __init__
    Shelf.__init__(self, dbm.open(filename, flag), protocol, writeback)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/dbm/__init__.py", line 91, in open
    "available".format(result))
```

**Comment by autoreleasefool** [comment]
Hey Jenny,
Not sure why you're seeing that error. This was the first time you ran the command? I've updated the README with some steps, if you wanna check those out. Can I ask what operating system you're on?

Also, thanks for trying to use the tool, I thought it was funny :P It won't actually order the pizza for you, but it should get you right to the last page and you can just hit "place order" for yourself if you feel so inclined.

**Comment by NavjotPanesar** [comment]
Is this fixed???
